<?php
// $Id$

/**
 * @file
 * Compass module compiles Sass stylesheets for themes.
 *
 * The shell execution functions were taken from ImageAPI module ImageMagick
 * toolkit
 */

/**
 * Implementation of hook_help().
 */
function compass_help($path, $arg) {
  switch ($path) {
    case 'admin/help#compass':
      $output = '<p>'. t('Compass module supports the !compass_link framework tool in your Drupal theme development workflow. Compass stylesheets are optionally compiled at cron runs or on demand. You must configure your theme\'s info file for the module to work.', array('!compass_link' => l('Compass', 'http://wiki.github.com/chriseppstein/compass'))) .'</p>';
      $output .= '<h2>'. t('Configuration') .'</h2>';
      $output .= '<p>'. t('Add this line to your theme\'s .info file') .'</p>';
      $output .= '<pre><code>compass[status] = 1</code></pre>';
      $output .= '<p>'. t('Other command line options can be specified using their long argument names with underscores ( %underscore ) instead of hyphens ( %hyphen ).', array('%underscore' => '_', '%hyphen' => '-')) .'</p>';
      $output .= '<pre><code>compass[sass_dir] = "src"</code></pre>';
      $output .= '<p>'. t('If you have used compass to create your theme stylesheets, you can rely on the config.rb in the theme\'s directory') .'</p>';
      return $output;
    default:
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function compass_menu() {
  $items = array();
  if (module_exists('devel')) {
    $items['devel/compass'] = array(
      'title' => 'Run Compass',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('compass_process'),
      'access arguments' => array('access devel information'),
      'menu_name' => 'devel',
      'file' => 'compass.pages.inc',
    );
  }
  $items['admin/settings/compass'] = array(
    'title' => 'Compass',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('compass_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'compass.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_menu_link_alter().
 *
 * Flag this link as needing alter at display time.
 * This is more robust that setting alter in hook_menu().
 * See devel_translated_menu_link_alter().
 *
 */
function compass_menu_link_alter(&$item, &$menu) {
  if ($item['link_path'] == 'devel/compass') {
    $item['options']['alter'] = TRUE;
  }
}

/**
 * Implementation of hook_translated_menu_item_alter().
 *
 * Append dynamic querystring 'destination' to several of our own menu items.
 *
 */
function compass_translated_menu_link_alter(&$item) {
  if ($item['href'] == 'devel/compass') {
    $item['localized_options']['query'] = drupal_get_destination();
  }
}

/**
 * Implementation of hook_cron().
 */
function compass_cron() {
  if (variable_get('compass_cron', TRUE)) {
    $themes = list_themes();
    foreach ($themes as $theme) {
      if ($theme->status && isset($theme->info['compass']['status'])) {
        _compass_update($theme->name, $output, $errors);
        watchdog('compass', 'Compass run on %theme', array('%theme' => $theme->info['name']));
      }
    }
  }
}

/**
 * Submit function
 */
function compass_process_submit($form, &$form_state) {
  if ($form_state['clicked_button']['#value'] == t('Compile')) {
    $form_state['rebuild'] = TRUE;
  }
}

function _compass_build_version($form_element, $form_state) {
  // make sure path is set and valid before running after build.
  if ($path_errors = _compass_check_path($form_state['values']['compass_path'])) {
    // check here is primarily for pre-existing bad settings...
    // the #validate should prevent users from adding bad paths.
    $form_element['compass_binary'] = array(
      '#value' => '<p class="error">'. implode('<br />', $path_errors) .'</p>',
    );
  }
  else {
    _compass_exec('version', $output, $errors);
    $form_element['compass_binary']['version'] = array(
      '#title' => t('Version information'),
      '#value' => '<pre>'. check_plain(trim($output)) .'</pre>',
      '#description' => t('The <kbd>compass</kbd> binary was located and return this version information.'),
    );
  }
  $form_element['compass_binary']['version']['#type'] = 'item';
  $form_element['compass_binary']['version']['#weight'] = -1;
  return $form_element;
}

function compass_validate_path($element, &$form_state) {
  $errors = _compass_check_path($element['#value']);
  if ($errors) {
    form_set_error($element['#parents'][0], implode('<br />', $errors));
  }
}

function _compass_check_path($path) {
  $errors = array();
  if (!is_file($path)) {
    $errors[] = t('The specified Compass path %file does not exist.', array('%file' => $path));
  }
  if (!$errors && !is_executable($path)) {
    $errors[] = t('The specified Compass path %file is not executable.', array('%file' => $path));
  }
  if ($errors && $open_basedir = ini_get('open_basedir')) {
    $errors[] = t('PHP\'s <a href="!open-basedir">open_basedir</a> security restriction is set to %open-basedir, which may be interfering with attempts to locate Compass.', array('%file' => $path, '%open-basedir' => $open_basedir, '!info-link' => url('http://php.net/features.safe-mode#ini.open-basedir')));
  }
  return $errors;
}

function _compass_update($theme) {
  $themes = list_themes();
  $theme = $themes[$theme];

  $command = 'compile '. getcwd() .'/'. dirname($theme->filename);

  $args = array();
  $args = $theme->info['compass'];
  unset($args['status']);
  $args['boring'] = '';
  $args['output_style'] = variable_get('compass_output_style', 'nested');
  $args['environment'] = variable_get('compass_environment', 'production');
  if (variable_get('compass_relative_assets', FALSE) === TRUE) {
    $args['relative_assets'] = variable_get('compass_relative_assets', FALSE);
  }
  $command_args = '';
  foreach ($args as $key => $value) {
    $key = str_replace('_', '-', $key);
    if (!empty($value)) {
      $command_args .= '--'. $key .' '. $value;
    }
    else {
      $command_args .= '--'. $key;
    }
    $command_args .= ' ';
  }
  return $command .' '. $command_args;
}

// http://wiki.github.com/chriseppstein/compass/command-line-tool

function _compass_exec($command, &$output, &$errors) {
  $compass_path = variable_get('compass_path', '/usr/bin/compass');
  $errors = _compass_check_path($compass_path);
  if ($errors) {
    watchdog('compass', '!errors', array('!errors' => implode('<br />', $errors)), WATCHDOG_ERROR);
    return FALSE;
  }

  // TODO determine whether this module has any hope of ever working on Windows
  if (strstr($_SERVER['SERVER_SOFTWARE'], 'Win32') || strstr($_SERVER['SERVER_SOFTWARE'], 'IIS')) {
    // Use Window's start command to avoid the "black window" from showing up:
    // http://us3.php.net/manual/en/function.exec.php#56599
    // Use /D to run the command from PHP's current working directory so the
    // file paths don't have to be absolute.
    $compass_path = 'start "window title" /D'. escapeshellarg(getcwd()) .' /B '. escapeshellarg($compass_path);
  }

  $descriptors = array(
    0 => array('pipe', 'r'), // stdin
    1 => array('pipe', 'w'), // stdout
    2 => array('pipe', 'w')  // stderr
  );
  if ($h = proc_open($compass_path .' '. $command, $descriptors, $pipes, $_SERVER['DOCUMENT_ROOT'])) {
    fclose($pipes[0]);
    stream_set_blocking($pipes[1], 0);
    stream_set_blocking($pipes[2], 0);

    $output = '';
    $errors = '';
    while (!feof($pipes[1]) || !feof($pipes[2])) {
      if (!feof($pipes[1])) {
        $output .= stream_get_contents($pipes[1]);
      }
      if (!feof($pipes[2])) {
        $errors .= stream_get_contents($pipes[2]);
      }
    }

    // Display debugging information to authorized users.
    if (variable_get('compass_debugging', FALSE) && user_access('administer site configuration')) {
      drupal_set_message(t('Compass command: @command', array('@command' => $compass_path .' '. $command)));
      drupal_set_message(t('Compass output: !output', array('!output' => '<pre>'. $output .'</pre>')));
    }

    if ($errors) {
      drupal_set_message(t('Compass reported an error: !error', array('!error' => '<pre>'. $errors .'</pre>')), 'error');
    }

    fclose($pipes[1]);
    fclose($pipes[2]);
    return proc_close($h);
  }
  return FALSE;
}

/**
 * Implement hook_theme_registry_alter().
 *
 * Devel module optionally resets the theme registry on each page request. Every
 * theme's cached registry is cleared, but only the active theme is rebuilt
 * for any given page request, so the key in the global $theme variable is
 * sufficient to check.
 */
function compass_theme_registry_alter(&$theme_registry) {
  global $theme;
  if (variable_get('devel_rebuild_theme_registry', FALSE) && variable_get('compass_devel_rebuild', FALSE)) {
    $themes = list_themes();
    if (isset($themes[$theme]->info['compass']['status'])) {
      $cmd = _compass_update($themes[$theme]->name);
      _compass_exec($cmd, $output, $errors);
      drupal_clear_css_cache();
    }
  }
}
